<?php
/** @var $block \Magento\Framework\View\Element\Template" */

/** @var \SysPerson\MagentoAcademy\Api\PersonFront\ConfigInterface $viewModel */
$viewModel = $block->getview_model();
$product = $viewModel->getProduct();
$sku = $product->getSku();
?>
<style>
    .size-selection {
        margin: 15px 0px;
    }
    .consulting-content {
        display: none;
    }
</style>
<div class="size-selection">
    <input type="button" value="Quick order">
</div>
<div class="consulting-content" id="consulting-content">
    <form action="personfrontend\save\save" method="post">
        <p>Name: <input type="text"   name="name"/></p>
        <p>Phone: <input type="text"  name="phone"/></p>
        <p>Email: <input  type="text"  name="email" /></p>
        <input type="hidden" name="sku" value=<?php echo $sku ;?>>
        <input type="submit" value="Send">
    </form>
    <!-- The codes below helps display a static block in the template phtml file-->
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('how-to-choose-the-right-size')->toHtml(); ?>
    <!-- We will create the block id how-to-choose-the-right-size in the backend later -->
</div>
<!-- You can learn How to use the Modal widget in the link https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget_modal.html -->
<!-- The javascript codes below helps to display the popup content -->
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ], function($, modal) {
        // declaring initial options
        var options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            title: '<?php echo __('Quick order'); ?>'
        };
        // Initialize the modal widget to the consulting content
        var slide = modal(options, $('#consulting-content'));
        // Whenever click on the text link How to choose the right size?
        $('.size-selection input').on('click', function() {
            // open the popup content
            $('#consulting-content').modal('openModal');
            return false;
        });
    });
</script>




